### ISSUE TITLE
Using a wrong UUID and key timeouts all operations

### ISSUE THREAD

**Issue by hugmanrique** [PlayPen/playpen-core#13]
Instead of timing out all the operations, I think a proper error message would be better.

Steps to reproduce:
- Set a wrong UUID and key
- `java -Dlog4j.configurationFile=../image/build-log.xml -jar "${PLAYPEN_HOME}/PlayPen-1.0.jar" cli list` will timeout instead of failing
- Set a correct UUID and key
- Previous command will work as expected

**Comment by redxdev** [comment]
I've updated the network coordinator + client logic a bit. The network coordinator will now shoot back an invalid message before closing the connection as an indication to the client that something is wrong (this is the only way to do so without a protocol change, which I'm not keen on doing at the moment).

The client will also now display a message when it receives something invalid, though it still won't exit until timeout with some commands. I'll be working on this next.

**Comment by redxdev** [comment]
`cli` commands should no longer wait if the connection is closed due to an invalid uuid/key. The fix requires updates to both network coordinators and the cli.

**Comment by hugmanrique** [comment]
Thank you for the fast fix! 😀
