### ISSUE TITLE
LocalCoordinator and Server have cyclic dependencies

### ISSUE THREAD

**Issue by hugmanrique** [PlayPen/playpen-core#14]
The `LocalCoordinator#hashCode()` method calculates the hashcode of the `servers` map which contains a collection of `Server`s for which their `hashcode` will be calculated. The issue is that the `Server` class keeps a reference to its LocalCoordinator and will call the `hashcode` method forever.

![StackOverflowException stacktrace](https://i.imgur.com/PfErGqk.png)

**Comment by redxdev** [comment]
Odd that I've never seen this before. I'll change `Server.hashCode` to be based purely on itself and `LocalCoordinator.getUuid()`.

**Comment by hugmanrique** [comment]
Thank you for the quick fix! 😁
